######################################################################
# Automatically generated by qmake (3.1) Sun Feb 21 17:11:53 2021
######################################################################

TEMPLATE = app
TARGET = server-echo-test
INCLUDEPATH += .

CONFIG += c++17

QT += network
QT += core

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS
DEFINES += QT_USE_QSTRINGBUILDER

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += constant/NetworkConstant.h \
    converter/MessageConverter.h \
    dto/NodeDto.h \
    network/service/TcpClient.h \
    network/service/message/MessageProcessingService.h \
    network/service/message/MessageProcessor.h \
    network/service/message/strategy/AntRouteBuilderService.h \
    network/service/message/strategy/NodeRegistrationService.h \
    network/service/message/strategy/NodeSharingService.h \
    network/service/message/strategy/TextMessageService.h \
    network/thread/messagethread.h \
    util/NetworkUtil.h \
    network/service/TcpServer.h \
    util/TerminalMenuThread.h \
    util/TimeUtil.h
SOURCES += main.cpp \
    constant/NetworkConstant.cpp \
    converter/MessageConverter.cpp \
    dto/NodeDto.cpp \
    network/service/TcpClient.cpp \
    network/service/message/MessageProcessingService.cpp \
    network/service/message/MessageProcessor.cpp \
    network/service/message/strategy/AntRouteBuilderService.cpp \
    network/service/message/strategy/NodeRegistrationService.cpp \
    network/service/message/strategy/NodeSharingService.cpp \
    network/service/message/strategy/TextMessageService.cpp \
    network/thread/messagethread.cpp \
    util/NetworkUtil.cpp \
    network/service/TcpServer.cpp \
    util/TerminalMenuThread.cpp \
    util/TimeUtil.cpp
